spring:
  application:
    name: cloud-eureka
eureka:
  instance:
  #    prefer-ip-address: true
  #    ip-address: 127.0.0.1
#???????
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      # 5 24
      defaultZone: http://eureka-7900:7900/eureka/,
      http://eureka-7901:7901/eureka/,
      http://eureka-7902:7902/eureka/
      #,
  server:
    # ?????????
    enable-self-preservation: true
    # ????????????
    renewal-percent-threshold: 0.85
    # server???????????
    eviction-interval-timer-in-ms: 1000
    # ????readOnly???
    use-read-only-response-cache: true
    # ?? readOnly
    response-cache-update-interval-ms: 1000

---
spring:
  profiles: 7900
server:
  port: 7900
eureka:
  instance:
    hostname: eureka-7900
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      # 5 24
      defaultZone: http://eureka-7900:7901/eureka/


---
spring:
  profiles: 7901
server:
  port: 7901
eureka:
  instance:
    hostname: eureka-7901
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      # 5 24
      defaultZone: http://eureka-7900:7900/eureka/
---
spring:
  profiles: 7902
server:
  port: 7902
eureka:
  instance:
    hostname: eureka-7902
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      # 5 24
      defaultZone: http://eureka-7900:7902/eureka/